name: scidart
description: Cross-platform scientific library for Dart.
version: 0.0.1-dev.2
homepage: https://github.com/angelopolotto/scidart
author: Ângelo Polotto <angelopolotto@gmail.com.br>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
